when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error

homepage:
    path: /
    controller: 'App\Controller\BitcoinController::index'