<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQOFZSoA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQOFZSoA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQOFZSoA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQOFZSoA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQOFZSoA\App_KernelDevDebugContainer([
    'container.build_hash' => 'QOFZSoA',
    'container.build_id' => '58aeda4d',
    'container.build_time' => 1668255712,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQOFZSoA');
